### ISSUE TITLE
Error running mongoose-gen

### ISSUE THREAD

**Issue by elewis33** [topliceanu/mongoose-gen#18]
Trying out mongoose-gen to see if I can save myself some time generating quite a few relatively large schemas. Getting this error after installing monoose-gen, mongoose and adapting your index.js example.

```code
    node_modules/mongoose-gen/lib/generator.js:173
    return new connection.Schema(definition, options);
                         ^
TypeError: Cannot read property 'Schema' of undefined
```
Is there something more I can furnish you to help troubleshoot this?

**Comment by topliceanu** [comment]
Hi @elewis33. Yeah, can you give me some details about your environment, more precisely the version of nodejs and mongoose you just installed?

**Comment by elewis33** [comment]
```shell
npm list mongoose -g
/usr/local/lib
├── mongoose@4.3.3 
└─┬ mongoose-gen@2.1.0
  └── mongoose@3.8.21 
node --version
v4.2.3
```

**Comment by topliceanu** [comment]
Right! Thanks for pointing this out!

It seems I need to do some work on it to make it compatible with mongoose
v4+ and node v4+. I can't give you a close ETA, because of the holidays,
but the new version should be out by the 4th of January.

If you want to, you can help out with that. There is a contribution guide
you may want to follow
https://github.com/topliceanu/mongoose-gen#contributing.

Again, thanks for reaching out,
Alex

On Tue, Dec 22, 2015 at 1:14 PM, elewis33 <notifications@github.com> wrote:

> npm list mongoose -g
> /usr/local/lib
> ├── mongoose@4.3.3
> └─┬ mongoose-gen@2.1.0
>   └── mongoose@3.8.21
> node --version
> v4.2.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topliceanu/mongoose-gen/issues/18#issuecomment-166613126>
> .
>



-- 
Alexandru Topliceanu

**Comment by topliceanu** [comment]
@elewis33 My worry was that the new versions of mongoose/node would not be backward compatible.
I updated to node lts v4.2.4 and mongoose v4.3.4. 
I checked the tests and the examples and they all work fine. 
Consequently, I published a new PATCH of this lib with latest mongoose package.

Looking at your error, it  may be the case that you are using the `getSchema` method without providing the mongoose connection object. See the [new api](https://github.com/topliceanu/mongoose-gen#api). This was not required in mongoose-gen v1, so it's a breaking change in v2. Passing an external connection instance gives more flexibility and makes testing easier. 

Is that the case in your code?
